'use strict';

/**
 * Post PR review: classic summary (#1086 style) + inline file comments for critical/warning.
 */
const fs = require('fs');
const { LEDGER_MARKER, isBotUser, pullNumberFromContext, normalizeTitle } = require('./lib/ledger');

const INLINE_CAP = 100;

function nearestChangedLine(changedLines, file, line) {
  const lines = changedLines[file];
  if (!lines?.length) return 0;
  if (line && lines.includes(line)) return line;
  if (!line) return lines[0];
  return lines.reduce(
    (best, candidate) => (Math.abs(candidate - line) < Math.abs(best - line) ? candidate : best),
    lines[0]
  );
}

function isValidFilePath(file) {
  return Boolean(file && (file.includes('/') || /\.[a-z0-9]+$/i.test(file)));
}

function isProgressComment(body) {
  return (
    body.includes('Code review in progress') ||
    body.includes('Code review complete') ||
    body.includes('Code review failed') ||
    body.includes('<!-- review-progress -->')
  );
}

function titleFromBody(body) {
  const m = body.match(/\*\*(?:CRITICAL|WARNING|NIT):\s*(.+?)\*\*/i);
  return m ? m[1].trim() : '';
}

function riskEmoji(risk) {
  const r = String(risk || '').toLowerCase();
  if (r === 'high') return '🔴';
  if (r === 'medium') return '🟡';
  return '🟢';
}

function decisionEmoji(decision) {
  const d = String(decision || '').toLowerCase();
  if (d === 'request_changes') return '🔴';
  if (d === 'approve') return '🟢';
  return '🟡';
}

function decisionLabel(decision) {
  const d = String(decision || '').toLowerCase();
  if (d === 'request_changes') return 'Request changes';
  if (d === 'approve') return 'Approve';
  return 'Comment';
}

function formatFindingBlock(f) {
  const sev = (f.severity || 'warning').toUpperCase();
  const icon = sev === 'CRITICAL' ? '🔴' : sev === 'NIT' ? 'ℹ️' : '🟡';
  const cat = f.category ? ` · _${f.category}_` : '';
  let block = `${icon} **${sev}: ${f.title}**${cat}\n\n${f.body || ''}`;
  if (f.file) block += `\n\n\`${f.file}${f.line ? `:${f.line}` : ''}\``;
  return block;
}

function formatReviewSummary(parsed, { tier = '', metrics = null } = {}) {
  const findings = parsed.findings || [];
  const critical = findings.filter((f) => f.severity === 'critical');
  const warning = findings.filter((f) => f.severity === 'warning');
  const nits = findings.filter((f) => f.severity === 'nit');

  const byCategory = {};
  for (const f of findings) {
    const cat = f.category || 'general';
    byCategory[cat] = (byCategory[cat] || 0) + 1;
  }
  const categoryLine = Object.entries(byCategory)
    .sort((a, b) => b[1] - a[1])
    .map(([cat, count]) => `${cat}: ${count}`)
    .join(' · ');

  const risk = parsed.risk || 'medium';
  const decision = parsed.decision || 'comment';

  let body = `## Automated Code Review\n\n`;
  body += `${riskEmoji(risk)} **Risk:** ${risk} · ${decisionEmoji(decision)} **Decision:** ${decisionLabel(decision)} · **Tier:** ${tier || 'n/a'}\n\n`;

  if (parsed.parseError) {
    if (parsed.recoveredFromPartialJson) {
      body += `> ⚠️ **Partial JSON recovery** — review timed out while writing JSON; structured findings were recovered from the truncated output.\n\n`;
    } else if (parsed.recoveredFromMarkdown) {
      body += `> ⚠️ **Recovered review** — JSON output was missing or empty; findings were parsed from the review log.\n\n`;
    } else if (metrics?.parseMismatch || parsed.parseMismatch) {
      body += `> ⚠️ **Parse mismatch** — the model analyzed issues but JSON had fewer findings; recovered from review log.\n\n`;
    } else {
      body += `> ⚠️ **Partial parse** — some output could not be structured. See workflow logs.\n\n`;
    }
  }
  if (metrics?.timedOut) {
    body += `> ⏱️ **Timed out** before finishing — re-run \`/review\` if findings look incomplete.\n\n`;
  }

  const summary =
    parsed.summary && parsed.summary !== 'Review output could not be parsed.'
      ? parsed.summary
      : findings.length === 0
        ? 'No outstanding findings.'
        : 'Review completed.';
  body += `**Summary:** ${summary}\n\n`;

  body += `**Findings:** ${findings.length} total — ${critical.length} critical, ${warning.length} warning, ${nits.length} nits\n`;
  if (categoryLine) body += `_By category — ${categoryLine}_\n\n`;

  if (nits.length > 0) {
    body += `<details>\n<summary>ℹ️ ${nits.length} nit(s) — suggestions only, no action required</summary>\n\n`;
    body += `| File | Line | Title |\n| --- | --- | --- |\n`;
    for (const f of nits) {
      body += `| \`${f.file || '—'}\` | ${f.line || '—'} | ${f.title} |\n`;
    }
    body += `\n</details>\n\n`;
  }

  body += `---\n_Generated by native \`sarvam-code exec review\` (tier: ${tier || 'n/a'}). Re-reviews cover the full PR diff._`;
  return body;
}

function reviewEventFromDecision(decision, hasCritical) {
  const d = String(decision || '').toLowerCase();
  if (hasCritical || d === 'request_changes') return 'REQUEST_CHANGES';
  if (d === 'approve') return 'APPROVE';
  return 'COMMENT';
}

function buildChangedLinesFromManifest() {
  const changedLines = {};
  if (!fs.existsSync('/tmp/diff-manifest.json')) return changedLines;

  const manifest = JSON.parse(fs.readFileSync('/tmp/diff-manifest.json', 'utf8'));
  for (const { file } of manifest) {
    const safe = file.replace(/[^a-zA-Z0-9._-]/g, '__');
    const patchPath = `/tmp/diff/${safe}.patch`;
    if (!fs.existsSync(patchPath)) continue;

    const patch = fs.readFileSync(patchPath, 'utf8');
    const lines = new Set();
    let newLine = 0;

    for (const line of patch.split('\n')) {
      const hunk = line.match(/^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@/);
      if (hunk) {
        newLine = parseInt(hunk[1], 10);
        continue;
      }
      if (line.startsWith('+++') || line.startsWith('---')) continue;
      if (line.startsWith('+')) {
        lines.add(newLine);
        newLine++;
      } else if (line.startsWith('-')) {
        // removed line
      } else if (line.startsWith(' ') || line.startsWith('\\')) {
        lines.add(newLine);
        newLine++;
      }
    }

    changedLines[file] = [...lines];
  }

  return changedLines;
}

function loadChangedLines() {
  if (fs.existsSync('/tmp/changed-lines.json')) {
    try {
      return JSON.parse(fs.readFileSync('/tmp/changed-lines.json', 'utf8'));
    } catch {
      /* fall through */
    }
  }
  return buildChangedLinesFromManifest();
}

async function cleanupOldReviews(github, context, { currentProgressId = 0 } = {}) {
  const { owner, repo } = context.repo;
  const pull_number = pullNumberFromContext(context);
  if (!pull_number) throw new Error('Could not resolve PR number from context');

  const existingKeys = new Set();
  let existingInline = 0;
  let page = 1;
  while (true) {
    const { data: comments } = await github.rest.pulls.listReviewComments({
      owner,
      repo,
      pull_number,
      per_page: 100,
      page,
    });
    if (comments.length === 0) break;
    for (const comment of comments) {
      if (!isBotUser(comment.user.login)) continue;
      existingInline++;
      existingKeys.add(`${comment.path}::${normalizeTitle(titleFromBody(comment.body))}`);
    }
    page++;
  }
  console.log(`Existing bot inline comments preserved: ${existingInline}`);

  const reviewQuery = `query($owner: String!, $repo: String!, $pr: Int!, $cursor: String) {
    repository(owner: $owner, name: $repo) {
      pullRequest(number: $pr) {
        reviews(first: 100, after: $cursor) {
          pageInfo { hasNextPage endCursor }
          nodes { id author { login } body }
        }
      }
    }
  }`;
  let reviewCursor = null;
  let minimizedReviews = 0;
  do {
    const result = await github.graphql(reviewQuery, {
      owner,
      repo,
      pr: pull_number,
      cursor: reviewCursor,
    });
    const reviews = result.repository.pullRequest.reviews;
    for (const review of reviews.nodes) {
      if (
        review.author &&
        isBotUser(review.author.login) &&
        review.body &&
        review.body.includes('Automated Code Review')
      ) {
        try {
          await github.graphql(
            `mutation($id: ID!) {
              minimizeComment(input: { subjectId: $id, classifier: OUTDATED }) { minimizedComment { isMinimized } }
            }`,
            { id: review.id }
          );
          minimizedReviews++;
        } catch (e) {
          console.log(`Could not minimize review ${review.id}: ${e.message}`);
        }
      }
    }
    reviewCursor = reviews.pageInfo.hasNextPage ? reviews.pageInfo.endCursor : null;
  } while (reviewCursor);

  let deletedSummary = 0;
  let deletedProgress = 0;
  let commentPage = 1;
  while (true) {
    const { data: issueComments } = await github.rest.issues.listComments({
      owner,
      repo,
      issue_number: pull_number,
      per_page: 100,
      page: commentPage,
    });
    if (issueComments.length === 0) break;
    for (const comment of issueComments) {
      if (comment.id === currentProgressId) continue;
      if (!isBotUser(comment.user.login) || !comment.body) continue;
      if (comment.body.includes(LEDGER_MARKER)) continue;

      const isSummary = comment.body.includes('Automated Code Review');
      const isProgress = isProgressComment(comment.body);
      if (!isSummary && !isProgress) continue;

      try {
        await github.rest.issues.deleteComment({ owner, repo, comment_id: comment.id });
        if (isSummary) deletedSummary++;
        if (isProgress) deletedProgress++;
      } catch (e) {
        console.log(`Could not delete issue comment ${comment.id}: ${e.message}`);
      }
    }
    commentPage++;
  }

  console.log(
    `Cleaned up: ${minimizedReviews} reviews minimized, ${deletedSummary} summaries deleted, ${deletedProgress} progress deleted`
  );
  return existingKeys;
}

function buildInlineComments(findings, changedLines, existingKeys) {
  const inlineCandidates = [...findings];

  const queued = [];
  const summaryOnlyFindings = [];

  for (const f of inlineCandidates) {
    const file = (f.file || '').trim();
    let line = f.line ? parseInt(f.line, 10) : 0;

    if (!isValidFilePath(file)) {
      summaryOnlyFindings.push(f);
      continue;
    }

    if (changedLines[file]?.length) {
      line = nearestChangedLine(changedLines, file, line);
    }

    if (!line || !changedLines[file]?.includes(line)) {
      summaryOnlyFindings.push(f);
      continue;
    }

    const key = `${file}::${normalizeTitle(f.title)}`;
    if (existingKeys.has(key)) {
      console.log(`Skipping duplicate inline: ${key}`);
      continue;
    }

    queued.push({
      finding: f,
      comment: {
        path: file,
        line,
        side: 'RIGHT',
        body: formatFindingBlock(f),
      },
    });
  }

  const overflow = queued.splice(INLINE_CAP);
  for (const { finding } of overflow) {
    summaryOnlyFindings.push(finding);
  }

  return {
    inlineComments: queued.map((q) => q.comment),
    summaryOnlyFindings,
  };
}

async function postSummaryReview(github, context, options) {
  const { owner, repo } = context.repo;
  const pull_number = pullNumberFromContext(context);
  if (!pull_number) throw new Error('Could not resolve PR number from context');

  const { parsed, commitId, tier, metrics, currentProgressId = 0 } = options;
  const findings = parsed.findings || [];

  const existingKeys = await cleanupOldReviews(github, context, { currentProgressId });
  const changedLines = loadChangedLines();
  const { inlineComments, summaryOnlyFindings } = buildInlineComments(
    findings,
    changedLines,
    existingKeys
  );

  let reviewBody = formatReviewSummary(parsed, { tier, metrics });

  if (summaryOnlyFindings.length > 0) {
    const extra = summaryOnlyFindings
      .map((f) => `- ${formatFindingBlock(f).replace(/\n/g, '\n  ')}`)
      .join('\n');
    reviewBody += `\n\n<details>\n<summary>Additional findings (no inline anchor)</summary>\n\n${extra}\n\n</details>`;
  }

  const hasCritical = findings.some((f) => f.severity === 'critical');
  const event = reviewEventFromDecision(parsed.decision, hasCritical);

  await github.rest.pulls.createReview({
    owner,
    repo,
    pull_number,
    commit_id: commitId,
    event,
    body: reviewBody.substring(0, 65536),
    comments: inlineComments,
  });

  console.log(
    `Posted review (event=${event}, ${findings.length} findings, ${inlineComments.length} inline, ${summaryOnlyFindings.length} summary-only)`
  );
  return { event, hasCritical, inlineCount: inlineComments.length };
}

module.exports = {
  formatFindingBlock,
  formatReviewSummary,
  reviewEventFromDecision,
  cleanupOldReviews,
  postSummaryReview,
};
