/**
 * Studio — motion-blurred forest stream scene for the login hero.
 *
 * Photo-sampled embroidered take of a horizontal-blur river-through-woods
 * photograph. Ships `studio-forest-stream-4` (Teal current).
 */

import { cell, defineMotifFromUnits, type BuiltMotif } from '../core';
import type { ImageStitchConfig } from '../imageStitch';
import { shade, type PlacedUnit, type UnitKey } from '../units';

export const STUDIO_FOREST_STREAM_GALLERY_GROUPS: readonly {
  id: string;
  label: string;
  prefix: string;
}[] = [{ id: 'forest-stream', label: 'Forest stream', prefix: 'studio-forest-stream-' }];

const COLLECTION = {
  collection: 'studio',
  collectionName: 'Studio',
  collectionDescription:
    'Sarvam Creative platform marks — brackets, voice, dubbing, and pinned shortlist.',
} as const;

/** Portrait sample grid from the 768×1024 reference. */
const SAMPLE_COLS = 40;
const SAMPLE_ROWS = 54;

/**
 * Horizontal cloth only — the photo's character is motion-blur streaks.
 * Avoid tweed/cross fills; they break the lateral grain.
 */
const STREAK_UNITS: UnitKey[] = ['hatchH', 'satin', 'hatchH', 'weave3'];
const WATER_UNITS: UnitKey[] = ['hatchH', 'satin', 'hatchH', 'satin'];
const SATIN_BIAS: UnitKey[] = ['satin', 'satin', 'hatchH', 'satin'];
const HATCH_BIAS: UnitKey[] = ['hatchH', 'hatchH', 'weave3', 'hatchH'];

type ForestStreamUnitBias = 'balanced' | 'satin' | 'hatch';

/** Props for the forest-stream weave. */
interface ForestStreamProps {
  /** Rendered pixels per cell (4 or 6). */
  cellPx: number;
  /** Cloth unit family for the horizontal grain. */
  unitBias: ForestStreamUnitBias;
  /**
   * How many cells along a row share one stitch unit (higher = longer streaks).
   */
  streakSegment: number;
  seed: number;
  /** Canopy brightness (− darker woods, + lime). */
  canopyBias: number;
  /** Water depth vs foam (− navy/teal, + mist/foam). */
  waterBias: number;
  /** Extra darkening on bank / shadow edges. */
  bankDarken: number;
  /** Push mids toward deep or bright (0 = flat, 1 = punchy). */
  contrast: number;
  /** Lift already-light water cells toward foam white. */
  foamLift: number;
  /** Cloth units in the weave pool — overrides `unitBias` when set. */
  units?: readonly UnitKey[];
}

const FOREST_STREAM_DEFAULTS: ForestStreamProps = {
  cellPx: 4,
  unitBias: 'balanced',
  streakSegment: 4,
  seed: 11,
  canopyBias: 0,
  waterBias: 0,
  bankDarken: 0.15,
  contrast: 0.2,
  foamLift: 0.1,
};

/** Quantized palette sampled from the reference photo. */
const COLORS = [
  '#152810',
  '#254818',
  '#3d6b28',
  '#5a8f2e',
  '#8fbf3a',
  '#b4d86a',
  '#2a3228',
  '#4a9aaa',
  '#2a7a88',
  '#1e5a68',
  '#1a2820',
  '#3a3428',
  '#7ec4d0',
  '#b8dce6',
  '#eef6f8',
  '#0f3040',
] as const;

/**
 * Row-major color indices into COLORS (hex chars 0–f).
 * Generated by downsampling the reference with a light horizontal blur.
 */
const CELL_HEX =
  '0001111222212222333333333331000000000000000000111111222233333333333210000000000000000010011122233344443333321000000000000000001111122323333333333322110000000000012111111111222233333333222211000000000001122333332222222333333332211000000000000001122333334333233333333221110000000000001122333333333322333222221101000000000000112222333333333333332221101000000000000001112222222222333333332111100000000000000112222233222123333334311000000000000000011223333333322222333321100000000000000011123333333332222222222210000000000000001122233333333222222222110000000000000001122223334443333321111110000000000000000112222333333333322211111100000000000000122233332222322121111111111000000000000022223333222223222111111111100000000000003333334333333333322111111110000000000000223334443333333333322212221000000000000022233333333333343322211111000000000000002223333344544444432221000000000000000000222233333444433332221211111000000000000022212112233333221111111111000000000000002221100011122222111111111100000000000000122222100011111221222322100000000000000012233322111122221111222110000000000000001122334322222332222223331000000000000000006123333344333223337777789896a000000000000011233445555547733888899996a000000000000066b22334755cccc7777789999600000000000001222223457cccddddcccc7788266660aa00001122333345555cddcccc77777891111666aa0000000122233455555cccccccccc778322b1666600000001275cdddeeeeddeeeeddddc32226000000000b2112cdddeeeeeeeeeeeeeedd7a16aa66a6a0003444345ddddeeeeeeeeeeddddcc9600000aa0000444455ddddeeeeeeeeeddccc77cc7992b2600000445555ddddddddddddccc77ccccccccc78600000455555dddddddddcccc777777cc77cc789a0aa00333555dddddddc7777ccccccccccccc778226666223555cccccc789988777cccccccccc7772229993337c338887789fff999987777ccccc77796a6a0222222299888789ffffff99988777ccc77789f6a0aaaa66699999999999f9ffff9998887777778890000000aaaffff99999fffaafff999877777777700000000000affffffffffffff99877ccccc7cc70000000000000affffffffffff9988777777777700000000000000aaaaafffffffffafff998777770000000000000000000aaaffffffaaaafff99877000000000000000000000aaafaafaaafffff999800000000000000000000000aaaaa0000aff9999800000000000000000000000a000000000aff999800000000000000000000000a0000000000000af9';

/** Row-major region tags: c=canopy, w=water, b=bank. */
const KIND =
  'bccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbcccccccccccccccccccccccccbbbbbbbbbbbbbbbcccccccccccccccccccccccccbbbbbbbbbbbbccbcccccccccccccccccccccccccccbbbbbbbbccccccccccccccccccccccccccccccccbbbbbbbbccccccccccccccccccccccccccccccccbbbbbbbbbbcccccccccccccccccccccccccccccbbbbbbbbbbcccccccccccccccccccccccccccccbbbbbbbbbbbbccccccccccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccbbbbbbbbbbbcccccccccccccccccccccccccccccbbbbbbbbbbbccccccccccccccccccccccccccbcbbbbbbbbbbbbccccccccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccbbbbbbbbbbbcccccccccccccccccccccccccccccbbbbbbbbbbbcccccccccccccccccccccccccccccbbbbbbbbbbbccccccccccccccccccccccccccccbbbbbbbbbbbbcccccccccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccbbbbbbbbbbbbbbbcccccccccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccbbbbbbbbbbbbbccccccbccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccbbbbbbbbbbbbbbbccccccccccccccccccccccccccbbbbbbbbbbbbbbbbccccccccccccccccccwwwwwwcwwcbbbbbbbbbbbbbbcccccccccccccccccwwwwccwcccbbbbbbbbbbbbccccccccccwwwwwwwwwwwwcccccbbbbbbbbbbbbcccccccccwwwwwwwwwwwwwwwwwccccccccbbbbcccccccccccwwwwwwwwwwwwwwwccccccccccbbbbbbbcccccccccwwwwwwwwwwwwwwwwcccccccccbbbbbbbcccwwwwwwwwwwwwwwwwwwwwcccccbbbbbbbbccccccwwwwwwwwwwwwwwwwwwwwwccccccccccbbbccccccwwwwwwwwwwwwwwwwwwwwwwcbbbbbcbbbbbccccccwwwwwwwwwwwwwwwwwwwwwwwwwwcccbbbbbccccccwwwwwwwwwwwwwwwwwwwwwwwwwwwwcbbbbbcccccwwwwwwwwwwwwwwwwwwwwwwwwwwwwwcbbbbbcccccwwwwwwwwwwwwwwwwwwwwwwwwwwwwwccccccccccwwwwwwwwwwcwwwwwwwwwwwwwwwwwwwcccwwwcccwwcccwwwwwwcccwwwwwwwwwwwwwwwwwwccccbccccccccwwwwwwwccccccwwwwwwwwwwwwwwwwccbbbcbccccccwwwwwwwwwccccccwwwwwwwwwwwwwwwbbbbbbbcccccccwwwwwccccbcccwwwwwwwwwwwwwbbbbbbbbbbbccccccccccccccwwwwwwwwwwwwwwwbbbbbbbbbbbbbcccccccccccccwwwwwwwwwwwwwwbbbbbbbbbbbbbbbbccccccccccccccccwwwwwwwwbbbbbbbbbbbbbbbbbbbbbcccccccbbbccccwwwwwbbbbbbbbbbbbbbbbbbbbbbbbcccccbbcccccwwwwbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccwwwwwbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccwwwwbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccw';

function n01(r: number, c: number, seed: number): number {
  const x = Math.sin(r * 127.1 + c * 311.7 + seed * 74.7) * 43758.5453;
  return x - Math.floor(x);
}

function pick<T>(arr: readonly T[], r: number, c: number, seed: number): T {
  return arr[Math.floor(n01(r, c, seed) * arr.length) % arr.length]!;
}

function clamp(t: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, t));
}

function luminance(hex: string): number {
  const n = parseInt(hex.slice(1), 16);
  const r = (n >> 16) & 255;
  const g = (n >> 8) & 255;
  const b = n & 255;
  return (r * 0.3 + g * 0.59 + b * 0.11) / 255;
}

function unitsFor(kind: string, bias: ForestStreamUnitBias): readonly UnitKey[] {
  if (kind === 'w') {
    if (bias === 'satin') return SATIN_BIAS;
    if (bias === 'hatch') return HATCH_BIAS;
    return WATER_UNITS;
  }
  if (bias === 'satin') return SATIN_BIAS;
  if (bias === 'hatch') return HATCH_BIAS;
  return STREAK_UNITS;
}

function tuneColor(base: string, kind: string, props: ForestStreamProps): string {
  let t = 0;
  if (kind === 'c') t += props.canopyBias * 0.45;
  if (kind === 'w') t += props.waterBias * 0.4;
  if (kind === 'b') t -= props.bankDarken * 0.55;
  // Soft bank edges that were tagged dark still pick up a little canopy bias
  if (kind === 'b' && props.canopyBias < 0) t += props.canopyBias * 0.2;

  const lum = luminance(base);
  if (kind === 'w' && lum > 0.55) t += props.foamLift * 0.4;
  if (props.contrast > 0) {
    t += (lum > 0.42 ? 1 : -1) * props.contrast * 0.28;
  }

  return shade(base, clamp(t, -0.85, 0.85));
}

function buildForestStream(props: ForestStreamProps): BuiltMotif {
  const units: PlacedUnit[] = [];
  const segment = Math.max(1, Math.round(props.streakSegment));

  for (let r = 0; r < SAMPLE_ROWS; r++) {
    for (let c = 0; c < SAMPLE_COLS; c++) {
      const i = r * SAMPLE_COLS + c;
      const kind = KIND[i]!;
      const base = COLORS[parseInt(CELL_HEX[i]!, 16)]!;
      // Dark forest edges were tagged bank for palette mood — stitch them as canopy
      // so the horizontal blur grain stays unbroken.
      const stitchKind = kind === 'b' ? 'c' : kind;
      const color = tuneColor(base, kind, props);
      const pool =
        props.units && props.units.length > 0 ? props.units : unitsFor(stitchKind, props.unitBias);
      const unit = pick(pool, r, Math.floor(c / segment), props.seed);
      units.push(cell(r, c, unit, color));
    }
  }

  return { cols: SAMPLE_COLS, rows: SAMPLE_ROWS, units };
}

type GalleryPreset = {
  id: string;
  name: string;
  props: ForestStreamProps;
};

const GALLERY_PRESETS: readonly GalleryPreset[] = [
  {
    id: 'studio-forest-stream-4',
    name: 'Forest stream — Teal current',
    props: {
      ...FOREST_STREAM_DEFAULTS,
      unitBias: 'satin',
      seed: 41,
      canopyBias: -0.05,
      waterBias: -0.08,
      foamLift: 0.05,
      contrast: 0.25,
      streakSegment: 5,
    },
  },
];

function motif(id: string, name: string, props: ForestStreamProps) {
  return defineMotifFromUnits({
    ...COLLECTION,
    id,
    name,
    cellPx: props.cellPx,
    build: () => buildForestStream(props),
  });
}

const CONFIGS_BY_ID = Object.fromEntries(
  GALLERY_PRESETS.map((preset) => [preset.id, motif(preset.id, preset.name, preset.props)])
) as Record<(typeof GALLERY_PRESETS)[number]['id'], ImageStitchConfig>;

/** Side-effect registration — shipped forest-stream mark in Studio. */
export const STUDIO_FOREST_STREAM_CONFIGS = GALLERY_PRESETS.map(
  (preset) => CONFIGS_BY_ID[preset.id]
);

/** Login hero — Teal current. */
export const studioForestStream4Mark = CONFIGS_BY_ID['studio-forest-stream-4'];
